sonar.projectKey=AswathiMavingal_platform-ui-products
sonar.organization=aswathimavingal
sonar.sources=src
sonar.tests=src
sonar.host.url=https://sonarcloud.io
sonar.token=${SONAR_TOKEN}
sonar.test.inclusions=**/*.spec.ts
sonar.javascript.lcov.reportPaths=coverage/lcov.info